version: '3.8'

services:
  app:
    build: .
    container_name: mamhoor_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # - JWT_SECRET=change_me_in_production
      # - DATABASE_URL="file:./dev.db" 
    volumes:
      - uploads_data:/app/public/uploads
      - prisma_data:/app/prisma
    restart: always

volumes:
  uploads_data:
  prisma_data:
